export const questions = [
  "What was the happiest moment of your year?",
  "When did you feel most at peace, and why?",
  "What was your biggest source of stress or worry this year?",
  "Did you experience any new emotions or feelings you hadn’t before?",
  "How well did you manage your mental health this year?",
  "Was there a time when you felt deeply grateful? Describe it.",
  "If you could sum up this year in one emotion, what would it be and why?",
  "Which relationship had the most positive impact on you this year?",
  "Was there a relationship you wished you had nurtured more? Why?",
  "Did you make any new meaningful connections this year?",
  "Was there a time when someone supported you in an unexpected way?",
  "Did you forgive someone or ask for forgiveness this year?",
  "What did you learn about yourself from your interactions with others?",
  "Who was your biggest cheerleader this year, and how did it affect you?",
  "What’s a skill or habit you improved or learned this year?",
  "What’s the biggest challenge you overcame this year?",
  "What was the most important decision you made, and how did it shape your year?",
  "Did you take any risks that paid off or taught you valuable lessons?",
  "Did you change your opinion on something, and what made you do so?",
  "Was there a project or goal you achieved that made you proud?",
  "What was a mistake you made, and what did you learn from it?",
  "How did you prioritize your time and energy this year?",
  "What’s the most vivid memory you created this year?",
  "Did you try anything for the first time? What was it like?",
  "What was your favorite place you visited this year, and why?",
  "Did you have any moments where you felt truly alive?",
  "What’s one thing you did this year that you’d love to do again?",
  "If you could change one thing about this year, what would it be and why?",
  "How has this year shaped your vision or goals for the future?",
  "What advice would you give to yourself for the coming year?",
];
