export const questions = [
    "What brings you the most joy in life?",
    // "What's a childhood memory that makes you smile?",
    // "What's something you're proud of that you rarely share?",
    // "What's a dream you've been hesitant to pursue?",
    // "When do you feel most at peace?",
    // "What's a small act of kindness that left a big impact on you?",
    // "What's a place that makes you feel completely yourself?",
    // "What's a skill or talent you have that might surprise others?",
    // "What's a challenge you've overcome that made you stronger?",
    // "What's a change you'd like to make in your life?",
    // "What's a belief you held that has evolved over time?",
    // "What's something you're looking forward to?",
    // "What's a quality you appreciate most in others?",
    // "What's a lesson life has taught you recently?",
    // "What's something you'd like to learn more about?",
    // "What's a tradition that holds special meaning for you?",
    // "What's a goal that excites you?",
    // "What's a moment when you felt truly proud of yourself?",
    // "What's something you value more now than you used to?",
    // "What's a relationship that has shaped who you are?",
    // "What's a fear you'd like to overcome?",
    // "What's something you do to show yourself kindness?",
    // "What's a memory that always makes you laugh?",
    // "What's something you're grateful for right now?",
    // "What's a piece of advice you'd give to your younger self?",
    // "What's something that brings you peace during difficult times?",
    // "What's a dream you have for your future?",
    // "What's a small pleasure that brightens your day?",
    // "What's something you've discovered about yourself recently?",
    // "What's a way you've grown in the past year?",
    // "What's something you appreciate about your journey so far?",
    // "What's a quality in yourself that you're proud of?",
    // "What's a hobby or activity that makes you lose track of time?",
    // "What's something you'd like to be remembered for?",
    // "What's a value that guides your decisions?",
    // "What's a change you've noticed in yourself over time?",
    // "What's something that always restores your energy?",
    // "What's a hope you have for the future?",
    // "What's something you've forgiven yourself for?",
    // "What's a dream you're ready to pursue?"
  ];